services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql_spring
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: rest_spring_boot
      TZ: UTC
    ports:
      - "3306:3306"
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --lower_case_table_names=1
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
