version: "3.9"

services:
  mysql:
    image: mysql:8.4           # escolha a versão que preferir
    container_name: mysql_spring
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin          # root / admin
      MYSQL_DATABASE: rest_spring_boot    # banco que seu app usa
      TZ: UTC
    ports:
      - "3306:3306"            # expõe para a máquina‑host
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
